### ISSUE TITLE
parse 数据可以是定义吗

### ISSUE THREAD

**Issue by jackdizhu** [vvpvvp/model#2]
"babel-cli": "^6.26.0",
"babel-preset-es2015": "^6.24.1",
"babel-core": "^6.26.0",
"chai": "^4.1.2",
"manba": "^1.0.1"

const __Model = require('../src/model');
let _dataM = new __Model({
  a: Number,
  b: String,
  c: Date,
  d: Boolean,
  e: Array,
  f: Object
});
let _r = _dataM.parse({
  a: 'sdf12asd',
  b: 12
});

parse 数据可以是这样的 吗
{ c: new Date, d: false, e: [], f: {}, a: 0, b: '12' }

**Comment by vvpvvp** [comment]
let _dataM = new __Model({
 a: Number,
 b: String,
 c:{
  type: Date,
  parse() {
    return new Date();
  }
 },
 d:{
  type: Boolean,
  default: false
 },
 e: Array,
 f: Object
});
