### ISSUE TITLE
哈喽，我想问一下为啥要定义自己的一套TYPE 

### ISSUE THREAD

**Issue by WangPanFJG** [vvpvvp/model#3]
![image](https://user-images.githubusercontent.com/28427901/42425727-7742b5d4-8353-11e8-9cf6-0e3d648126e3.png)
不太明白， js不是有自己的类型吗？ Number, String...............

**Comment by vvpvvp** [comment]
是有的，只是我当时写的时候，想要的是唯一性，刚好看ES6看的比较多，所以用的是Symbol，其实我觉得都可以。
当然，后期就会直接修改成Number, String这些对象。

**Comment by WangPanFJG** [comment]
@vvpvvp 好的，灰常感谢 ^_^
