### ISSUE TITLE
请问怎么集成到vue中

### ISSUE THREAD

**Issue by kuangshp** [vvpvvp/model#5]
我直接集成到vue中就是不行

**Comment by kuangshp** [comment]
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    {{a}}
   {{a.b}}
    <hr>
  </div>
</template>

<script>
import Test1 from './../model/Test1.js';
let a = Test1.parse({});
console.log(a.b);
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
     a,
    }
  }
}
</script>

--------------
import Model from "js-model";
export default new Model({
  a: {
    b: {
        c: Number
    },
    d: String
  },
})

--------------

我这样输出a是一个对象,但是a.b就是undefined

**Comment by kuangshp** [comment]
```js
import Model from "js-model";
export default new Model({
  a: {
    b: {
        c: Number
    },
    d: String
  },
})
```
----
```html
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    {{a}}
    <hr>
  </div>
</template>

<script>
import Test1 from './../model/Test1.js';
let a = Test1.parse({});
console.log(a.b);
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```
---
我这样输出a是一个对象,但是a.b就是undefined

**Comment by vvpvvp** [comment]
``` html

<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    {{a}}
    <hr>
  </div>
</template>

<script>
import Test1 from './../model/Test1.js';

export default {
  name: 'HelloWorld',
  data () {
    return {
     a: Test1.parse({}),
      msg: 'Welcome to Your Vue.js App',
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```

我写的是伪代码，你也不用用的这么直接啊？

**Comment by kuangshp** [comment]
知道是伪代码，我也是看到这个东西比较好，尝试下，今后用在项目中，能发下你使用的代码出来看下吗

**Comment by vvpvvp** [comment]
你按照上面我个的代码就可以了，你也可以等等，我整理一个vue的使用基础sample，下午发出来。

**Comment by kuangshp** [comment]
不可以，是不是还要在哪里配置，我最近打算把数据层与视图层分开，等待sample

**Comment by kuangshp** [comment]
我看了下，好像用途不是很大,依然要去判断，不是跟你掘金上说的，不需要判断,方便加你好友再研究下吗

**Comment by vvpvvp** [comment]
你微信多少？

**Comment by vvpvvp** [comment]
聊天室：https://discord.gg/VUZbFmd

**Comment by kuangshp** [comment]
jianshuihen我的微信号，谢谢
