### ISSUE TITLE
parse 结果是 [object Object]

### ISSUE THREAD

**Issue by imageslr** [vvpvvp/model#7]
demo： https://codepen.io/anon/pen/qyXjyj

模型定义：

```JS
let User = new Model({
  id: 0,
  follower_num: 0,
  following_num: 0,
  is_following: false,
  type: String,
  real_name: String,
  avatar_url: String,
  title: String,
  introduction: String,
})
```

我发现把 `type: String` 改成 `type1: String` 就没问题了，问题可能出现在对属性名的判断上？

另外，请问能否支持Boolean类型的定义？默认false。

**Comment by vvpvvp** [comment]
new Model({
  test: {
    type: String,
    default: 'ab'
  },
  boolean: Boolean
})

主要是type是关键字，我们也可以通过上面的方式定义test为String，默认值为ab。
不知道你有没有什么好的建议？
Boolean类型可以的。

**Comment by vvpvvp** [comment]
请更新版本

**Comment by imageslr** [comment]
好的，辛苦了~
